### ISSUE TITLE
correct video name

### ISSUE THREAD

**Issue by ruiguo-bio** [Gaarv/kadenze-dl#2]
Thank for you good job! I find the video name is directly got from the download file name e.g. 3.1_2_720.mp4, and it's better replaced by the meaningful name in the media queue.

Also I hope when downloading, it will show the percentage bar of each downloading file.  If one file is not downloaded successfully, it should not be saved so the next time it can be downloaded again, not just skipped. Many of my downloaded file is not completed, due to my poor network :(

**Comment by Gaarv** [comment]
Getting the proper video filename might be tricky, since it's not in the json containing video information, but I will give it a try.

On the other side, I also wanted to have a progress bar so it has been added :) Parallelized download has been disabled for now, working on how to sync the progress bar between downloads in the console.

**Comment by ruiguo-bio** [comment]
Thank you. I think coursera-dl may have all the behavior I suggested. If possible, you can take a look on their code :)

**Comment by ruiguo-bio** [comment]
The progress bar is ok at the beginning of running, but after sometime it keeps output on new lines, like the picture below:
[
![screen shot 2016-12-07 at 16 16 30](https://cloud.githubusercontent.com/assets/20548903/20959957/d2732d36-bc98-11e6-99e8-21b966850898.png)
](url)

The file names when the issue happens is like 2.11_1_720, a "_" suffix. Is that the problem?

**Comment by Gaarv** [comment]
I will take a look at this, I might switch to the tqdm library since its so well done. Thanks for reporting !

**Comment by ruiguo-bio** [comment]
Another interesting issue is when I download one machine learning for musicians course, it split the 8 introduction section videos into 8 folders, like the picture below:
![1](https://cloud.githubusercontent.com/assets/20548903/21070588/1b1eeef4-bec3-11e6-892b-0a95a9461ae9.png)

 Those videos are all in the first section, so they should be in the 1-introduction folder

**Comment by Gaarv** [comment]
Progress bar issue should be fixed. It seems to be the buffering behaving differently on OSX, I use print(s, flush=True) now instead of sys.stdout.flush() so that should take care of it.

The naming issue is due to this course not following naming convention used on other courses videos (first number in the filename should be session number) but found a workaround, and I downloaded the introduction at only one place :)

Still need more time for implementing proper video names as I don't want anyone to redownload all video so will need to figure also a way to rename them.

**Comment by ruiguo-bio** [comment]
The issue on Dec 7, 2016 comment appears again.

**Comment by nazikus** [comment]
any progress on naming files? maybe you could make in optional through configuration?
really inconvenient to browse through cryptic files names when downloaded.

**Comment by Gaarv** [comment]
Honestly, I haven't looked hard into it, apologies :) The optional parameter is a great idea, as the default download would still be usable if getting names failed.

I will get some testing done this week and let you know.

**Comment by Gaarv** [comment]
Seems like Kadenze included the video title in the json data since last time I checked, and I've got good results getting them. 

I will be doing more checks on differents courses by downloading them multiple times and will be pushing the changes later this week if all ok.

**Comment by Gaarv** [comment]
Videos will now be named by their respective videos titles (activated by default in configuration) when possible. It should always be the case tho, haven't encountered any issue so far on several courses.

Also a new dependency needs to be installed, by running "pip install -r requirements.txt" on a refreshed clone repository.

Let me know if any issue :)

**Comment by nazikus** [comment]
works great. thanks for prompt response.
